services:
  - type: web
    name: luffy
    runtime: node
    repo: https://github.com/VHASH173/luffy.git
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: JWT_SECRET
        generateValue: true
      - key: FIREBASE_PROJECT_ID
        value: luffy-luxe-store
      - key: FIREBASE_CLIENT_EMAIL
        value: firebase-adminsdk-fbsvc@luffy-luxe-store.iam.gserviceaccount.com
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_PRIVATE_KEY_ID
        value: 6e3e646141e131e7f10bc04cb3bb7cb8effbbb51
